INSERT INTO PRACTICE_CATEGORY (ID, NAME)
VALUES ( 1001, 'define' );
INSERT INTO PRACTICE_CATEGORY (ID, NAME)
VALUES ( 1002, 'make' );
INSERT INTO PRACTICE_CATEGORY (ID, NAME)
VALUES ( 1003, 'deliver');