INSERT INTO PRACTICE_CATEGORY (ID, NAME)
VALUES ( 1001, 'define' );
INSERT INTO PRACTICE_CATEGORY (ID, NAME)
VALUES ( 1002, 'make' );
INSERT INTO PRACTICE_CATEGORY (ID, NAME)
VALUES ( 1003, 'deliver');

INSERT INTO PRACTICE_SUB_CATEGORY (ID, NAME, DESCRIPTION, PRACTICE_CATEGORY_ID)
VALUES(2001, 'scope', 'scope practice', 1001);
INSERT INTO PRACTICE_SUB_CATEGORY (ID, NAME, DESCRIPTION, PRACTICE_CATEGORY_ID)
VALUES(2002, 'architect', 'architect practice', 1002);
INSERT INTO PRACTICE_SUB_CATEGORY (ID, NAME, DESCRIPTION, PRACTICE_CATEGORY_ID)
VALUES(2003, 'release', 'release practice', 1003);

INSERT INTO PRACTICE (ID, NAME, DESCRIPTION, PRACTICE_SUB_CATEGORY_ID)
VALUES(3001, 'practice 1', 'practice 1 description', 2001);
INSERT INTO PRACTICE (ID, NAME, DESCRIPTION, PRACTICE_SUB_CATEGORY_ID)
VALUES(3002, 'practice 2', 'practice 2 description', 2002);
INSERT INTO PRACTICE (ID, NAME, DESCRIPTION, PRACTICE_SUB_CATEGORY_ID)
VALUES(3003, 'practice 3', 'practice 2 description', 2003);