INSERT INTO PRACTICE_CATEGORY (ID, NAME)
VALUES ( 1001, 'define' );
INSERT INTO PRACTICE_CATEGORY (ID, NAME)
VALUES ( 1002, 'make' );
INSERT INTO PRACTICE_CATEGORY (ID, NAME)
VALUES ( 1003, 'deliver');

INSERT INTO PRACTICE (ID, NAME, DESCRIPTION, CATEGORY)
VALUES(2001, 'scope', 'scope practice', 1001);
INSERT INTO PRACTICE (ID, NAME, DESCRIPTION, CATEGORY)
VALUES(2002, 'architect', 'architect practice', 1002);
INSERT INTO PRACTICE (ID, NAME, DESCRIPTION, CATEGORY)
VALUES(2003, 'release', 'release practice', 1003);